<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>images\snake.ico</ApplicationIcon>
    <Version>1.0.2</Version>
    <Company>Radish</Company>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="images\blueToken3.png" />
    <None Remove="images\board.png" />
    <None Remove="images\dice.png" />
    <None Remove="images\grayToken3.png" />
    <None Remove="images\greenToken3.png" />
    <None Remove="images\purpleToken3.png" />
    <None Remove="images\redToken3.png" />
    <None Remove="images\soundOff.png" />
    <None Remove="images\soundOn.png" />
    <None Remove="sounds\applause.wav" />
    <None Remove="sounds\gameover.wav" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="images\snake.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="System.Speech" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="images\blueToken3.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\board.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\dice.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\grayToken3.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\greenToken3.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\purpleToken3.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\redToken3.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\soundOff.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\soundOn.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="sounds\applause.wav">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="sounds\gameover.wav">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="images\blueToken.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="images\blueToken2.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="images\grayToken.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="images\grayToken2.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="images\greenToken.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="images\greenToken2.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="images\purpleToken.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="images\purpleToken2.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="images\redToken.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="images\redToken2.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
